# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTbglconverter.ui'
#
# Created: Sun Mar  8 19:54:57 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_QtBGLConverter(object):
    def setupUi(self, QtBGLConverter):
        QtBGLConverter.setObjectName("QtBGLConverter")
        QtBGLConverter.resize(555, 794)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QtBGLConverter.sizePolicy().hasHeightForWidth())
        QtBGLConverter.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(QtBGLConverter)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputFileBox = QtGui.QGroupBox(QtBGLConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFileBox.sizePolicy().hasHeightForWidth())
        self.inputFileBox.setSizePolicy(sizePolicy)
        self.inputFileBox.setObjectName("inputFileBox")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.inputFileBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.inputFileText = QtGui.QLineEdit(self.inputFileBox)
        self.inputFileText.setObjectName("inputFileText")
        self.horizontalLayout_7.addWidget(self.inputFileText)
        self.inputBrowseButton = QtGui.QPushButton(self.inputFileBox)
        self.inputBrowseButton.setObjectName("inputBrowseButton")
        self.horizontalLayout_7.addWidget(self.inputBrowseButton)
        self.verticalLayout_2.addWidget(self.inputFileBox)
        self.outputDirectoryBox = QtGui.QGroupBox(QtBGLConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectoryBox.sizePolicy().hasHeightForWidth())
        self.outputDirectoryBox.setSizePolicy(sizePolicy)
        self.outputDirectoryBox.setObjectName("outputDirectoryBox")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.outputDirectoryBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.outputDirectoryText = QtGui.QLineEdit(self.outputDirectoryBox)
        self.outputDirectoryText.setObjectName("outputDirectoryText")
        self.horizontalLayout_8.addWidget(self.outputDirectoryText)
        self.outputBrowseButton = QtGui.QPushButton(self.outputDirectoryBox)
        self.outputBrowseButton.setObjectName("outputBrowseButton")
        self.horizontalLayout_8.addWidget(self.outputBrowseButton)
        self.verticalLayout_2.addWidget(self.outputDirectoryBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputTypeBox = QtGui.QGroupBox(QtBGLConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTypeBox.sizePolicy().hasHeightForWidth())
        self.outputTypeBox.setSizePolicy(sizePolicy)
        self.outputTypeBox.setObjectName("outputTypeBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.outputTypeBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ubglRadio = QtGui.QRadioButton(self.outputTypeBox)
        self.ubglRadio.setObjectName("ubglRadio")
        self.verticalLayout_3.addWidget(self.ubglRadio)
        self.dicRadio = QtGui.QRadioButton(self.outputTypeBox)
        self.dicRadio.setObjectName("dicRadio")
        self.verticalLayout_3.addWidget(self.dicRadio)
        self.opfRadio = QtGui.QRadioButton(self.outputTypeBox)
        self.opfRadio.setObjectName("opfRadio")
        self.verticalLayout_3.addWidget(self.opfRadio)
        self.mobiRadio = QtGui.QRadioButton(self.outputTypeBox)
        self.mobiRadio.setObjectName("mobiRadio")
        self.verticalLayout_3.addWidget(self.mobiRadio)
        self.horizontalLayout.addWidget(self.outputTypeBox)
        self.languageOptionsBox = QtGui.QGroupBox(QtBGLConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageOptionsBox.sizePolicy().hasHeightForWidth())
        self.languageOptionsBox.setSizePolicy(sizePolicy)
        self.languageOptionsBox.setObjectName("languageOptionsBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.languageOptionsBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dictionaryLanguageText = QtGui.QLabel(self.languageOptionsBox)
        self.dictionaryLanguageText.setWordWrap(False)
        self.dictionaryLanguageText.setObjectName("dictionaryLanguageText")
        self.horizontalLayout_4.addWidget(self.dictionaryLanguageText)
        self.dictionaryLanguageBox = QtGui.QComboBox(self.languageOptionsBox)
        self.dictionaryLanguageBox.setObjectName("dictionaryLanguageBox")
        self.horizontalLayout_4.addWidget(self.dictionaryLanguageBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputLanguageText = QtGui.QLabel(self.languageOptionsBox)
        self.inputLanguageText.setWordWrap(False)
        self.inputLanguageText.setObjectName("inputLanguageText")
        self.horizontalLayout_5.addWidget(self.inputLanguageText)
        self.inputLanguageBox = QtGui.QComboBox(self.languageOptionsBox)
        self.inputLanguageBox.setObjectName("inputLanguageBox")
        self.horizontalLayout_5.addWidget(self.inputLanguageBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.outputLanguageText = QtGui.QLabel(self.languageOptionsBox)
        self.outputLanguageText.setWordWrap(False)
        self.outputLanguageText.setObjectName("outputLanguageText")
        self.horizontalLayout_6.addWidget(self.outputLanguageText)
        self.outputLanguageBox = QtGui.QComboBox(self.languageOptionsBox)
        self.outputLanguageBox.setObjectName("outputLanguageBox")
        self.horizontalLayout_6.addWidget(self.outputLanguageBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.languageOptionsBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtGui.QGroupBox(QtBGLConverter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.coverImageText = QtGui.QLineEdit(self.groupBox_6)
        self.coverImageText.setObjectName("coverImageText")
        self.horizontalLayout_11.addWidget(self.coverImageText)
        self.coverImageBrowseButton = QtGui.QPushButton(self.groupBox_6)
        self.coverImageBrowseButton.setObjectName("coverImageBrowseButton")
        self.horizontalLayout_11.addWidget(self.coverImageBrowseButton)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.unicodeCheckBox = QtGui.QCheckBox(QtBGLConverter)
        self.unicodeCheckBox.setChecked(True)
        self.unicodeCheckBox.setObjectName("unicodeCheckBox")
        self.horizontalLayout_2.addWidget(self.unicodeCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.filtersBox = QtGui.QGroupBox(QtBGLConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtersBox.sizePolicy().hasHeightForWidth())
        self.filtersBox.setSizePolicy(sizePolicy)
        self.filtersBox.setObjectName("filtersBox")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.filtersBox)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.filtersList = QtGui.QListWidget(self.filtersBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtersList.sizePolicy().hasHeightForWidth())
        self.filtersList.setSizePolicy(sizePolicy)
        self.filtersList.setMaximumSize(QtCore.QSize(16777215, 100))
        self.filtersList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.filtersList.setObjectName("filtersList")
        self.horizontalLayout_12.addWidget(self.filtersList)
        self.verticalLayout_2.addWidget(self.filtersBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mobiOptions = QtGui.QGroupBox(QtBGLConverter)
        self.mobiOptions.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mobiOptions.sizePolicy().hasHeightForWidth())
        self.mobiOptions.setSizePolicy(sizePolicy)
        self.mobiOptions.setObjectName("mobiOptions")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.mobiOptions)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textLabel4 = QtGui.QLabel(self.mobiOptions)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.horizontalLayout_9.addWidget(self.textLabel4)
        self.compressionComboBox = QtGui.QComboBox(self.mobiOptions)
        self.compressionComboBox.setMaxCount(3)
        self.compressionComboBox.setObjectName("compressionComboBox")
        self.compressionComboBox.addItem(QtCore.QString())
        self.compressionComboBox.addItem(QtCore.QString())
        self.compressionComboBox.addItem(QtCore.QString())
        self.horizontalLayout_9.addWidget(self.compressionComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textLabel5 = QtGui.QLabel(self.mobiOptions)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.horizontalLayout_10.addWidget(self.textLabel5)
        self.securityComboBox = QtGui.QComboBox(self.mobiOptions)
        self.securityComboBox.setMaxCount(3)
        self.securityComboBox.setObjectName("securityComboBox")
        self.securityComboBox.addItem(QtCore.QString())
        self.securityComboBox.addItem(QtCore.QString())
        self.securityComboBox.addItem(QtCore.QString())
        self.horizontalLayout_10.addWidget(self.securityComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3.addWidget(self.mobiOptions)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.generateButton = QtGui.QPushButton(QtBGLConverter)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        self.exitButton = QtGui.QPushButton(QtBGLConverter)
        self.exitButton.setMouseTracking(False)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.consoleBox = QtGui.QGroupBox(QtBGLConverter)
        self.consoleBox.setObjectName("consoleBox")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.consoleBox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.console = QtGui.QPlainTextEdit(self.consoleBox)
        self.console.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setProperty("cursor", QtCore.QVariant(QtCore.Qt.IBeamCursor))
        self.console.setAcceptDrops(False)
        self.console.setTabChangesFocus(True)
        self.console.setReadOnly(True)
        self.console.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.console.setObjectName("console")
        self.horizontalLayout_14.addWidget(self.console)
        self.verticalLayout_2.addWidget(self.consoleBox)

        self.retranslateUi(QtBGLConverter)
        self.compressionComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtBGLConverter)

    def retranslateUi(self, QtBGLConverter):
        QtBGLConverter.setWindowTitle(QtGui.QApplication.translate("QtBGLConverter", "QtBGLConverter", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFileBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Input File:", None, QtGui.QApplication.UnicodeUTF8))
        self.inputBrowseButton.setText(QtGui.QApplication.translate("QtBGLConverter", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.outputDirectoryBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Output Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputBrowseButton.setText(QtGui.QApplication.translate("QtBGLConverter", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTypeBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Output format:", None, QtGui.QApplication.UnicodeUTF8))
        self.ubglRadio.setText(QtGui.QApplication.translate("QtBGLConverter", "ubgl", None, QtGui.QApplication.UnicodeUTF8))
        self.dicRadio.setText(QtGui.QApplication.translate("QtBGLConverter", "dic", None, QtGui.QApplication.UnicodeUTF8))
        self.opfRadio.setText(QtGui.QApplication.translate("QtBGLConverter", "opf", None, QtGui.QApplication.UnicodeUTF8))
        self.mobiRadio.setText(QtGui.QApplication.translate("QtBGLConverter", "mobi", None, QtGui.QApplication.UnicodeUTF8))
        self.languageOptionsBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Language options:", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionaryLanguageText.setText(QtGui.QApplication.translate("QtBGLConverter", "Dictionary language", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLanguageText.setText(QtGui.QApplication.translate("QtBGLConverter", "Input language", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLanguageText.setText(QtGui.QApplication.translate("QtBGLConverter", "Output language", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Cover image (recommended 600x800):", None, QtGui.QApplication.UnicodeUTF8))
        self.coverImageBrowseButton.setText(QtGui.QApplication.translate("QtBGLConverter", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.unicodeCheckBox.setText(QtGui.QApplication.translate("QtBGLConverter", "Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.filtersBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Filters (select to apply):", None, QtGui.QApplication.UnicodeUTF8))
        self.mobiOptions.setTitle(QtGui.QApplication.translate("QtBGLConverter", "mobi options:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("QtBGLConverter", "Compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.setItemText(0, QtGui.QApplication.translate("QtBGLConverter", "No compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.setItemText(1, QtGui.QApplication.translate("QtBGLConverter", "Standard compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionComboBox.setItemText(2, QtGui.QApplication.translate("QtBGLConverter", "Mobipocket huffdic compression", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5.setText(QtGui.QApplication.translate("QtBGLConverter", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.securityComboBox.setItemText(0, QtGui.QApplication.translate("QtBGLConverter", "No security", None, QtGui.QApplication.UnicodeUTF8))
        self.securityComboBox.setItemText(1, QtGui.QApplication.translate("QtBGLConverter", "Encrypted content", None, QtGui.QApplication.UnicodeUTF8))
        self.securityComboBox.setItemText(2, QtGui.QApplication.translate("QtBGLConverter", "PID secured (retargetable)", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setText(QtGui.QApplication.translate("QtBGLConverter", "Generate it", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("QtBGLConverter", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleBox.setTitle(QtGui.QApplication.translate("QtBGLConverter", "Console:", None, QtGui.QApplication.UnicodeUTF8))

